export const COMMON_ERROR_TOKEN_EXPIRED = "COMMON_ERROR_TOKEN_EXPIRED";
export const COMMON_ERROR_CANNOT_USE_PREVIOUS_PASSWORDS =
  "COMMON_ERROR_CANNOT_USE_PREVIOUS_PASSWORDS";
export const COMMON_ERROR_SAME_PASSWORD = "COMMON_ERROR_SAME_PASSWORD";
export const COMMON_ERROR_SYSTEM_VERSION_MISMATCH =
  "COMMON_ERROR_SYSTEM_VERSION_MISMATCH";
export const COMMON_ERROR_USER_VERSION_MISMATCH =
  "COMMON_ERROR_USER_VERSION_MISMATCH";
export const COMMON_ERROR_INVALID_TOKEN = "COMMON_ERROR_INVALID_TOKEN";
export const COMMON_ERROR_MISSING_COOKIE_IN_TOKEN =
  "COMMON_ERROR_MISSING_COOKIE_IN_TOKEN";
export const COMMON_ERROR_INVALID_REFRESH_TOKEN =
  "COMMON_ERROR_INVALID_REFRESH_TOKEN";
export const LEAVE_ERROR_NUMBER_OF_DAYS_CANNOT_BE_LESS_THAN_USED_DAYS =
  "LEAVE_ERROR_NUMBER_OF_DAYS_CANNOT_BE_LESS_THAN_USED_DAYS";
export const COMMON_ERROR_OLD_PASSWORD_INCORRECT =
  "COMMON_ERROR_OLD_PASSWORD_INCORRECT";
