export const USER_BULK_HEADERS = [
  "title",
  "firstName",
  "middleName",
  "lastName",
  "workEmail",
  "gender",
  "birthDate",
  "nationality",
  "nin",
  "maritalStatus",
  "personalEmail",
  "phoneDialCode",
  "phone",
  "address",
  "addressLine2",
  "city",
  "country",
  "state",
  "postalCode",
  "linkedIn",
  "facebook",
  "instagram",
  "x",
  "bloodGroup",
  "allergies",
  "dietaryRestrictions",
  "tshirtSize",
  "name",
  "emergencyRelationship",
  "contactNoDialCode",
  "contactNo",
  "identificationNo",
  "employmentAllocation",
  "joinedDate",
  "teams",
  "primaryManager",
  "startDate",
  "endDate",
  "timeZone",
  "workLocation",
  "employeeType",
  "jobFamilyId",
  "jobTitleId",
  "ssn",
  "ethnicity",
  "eeo",
  "passportNo"
];

export const DATE_FORMAT = {
  YYYY_MM_DD_SLASH: "yyyy/MM/dd",
  YYYY_MM_DD_DASH: "yyyy-MM-dd",
  YYYY_M_D_SLASH: "yyyy/M/d",
  YYYY_M_D_DASH: "yyyy-M-d",
  MM_DD_YYYY_SLASH: "MM/dd/yyyy",
  MM_D_YYYY_DASH: "MM-d-yyyy",
  DD_MM_YYYY_SLASH: "dd/MM/yyyy",
  DD_MM_YYYY_DASH: "dd-MM-yyyy",
  MM_DD_YYYY_DASH: "MM-dd-yyyy",
  M_D_YYYY_SLASH: "M/d/yyyy",
  D_M_YYYY_SLASH: "d/M/yyyy",
  YYYY_DD_MM_SLASH: "yyyy/dd/MM",
  YYYY_DD_MM_DASH: "yyyy-dd-MM"
};
