export const WORK_LOCATION_PAGE_SIZE = 8;
export const WORK_LOCATION_SEARCH_DEBOUNCE_MS = 500;
export const MIN_RADIUS = 100;
export const MAX_RADIUS = 2000;

export const COMMON_ERROR_WORK_LOCATION_NAME_ALREADY_EXISTS =
  "COMMON_ERROR_WORK_LOCATION_NAME_ALREADY_EXISTS";
