export enum TitleEnum {
  MR = "MR",
  MRS = "MRS",
  MISS = "MISS"
}

export enum GenderEnum {
  MALE = "MALE",
  FEMALE = "FEMALE",
  OTHER = "OTHER"
}

export enum RelationshipTypes {
  SPOUSE = "SPOUSE",
  CHILD = "CHILD",
  PARENT = "PARENT",
  FAMILY = "FAMILY",
  FRIEND = "FRIEND",
  GUARDIAN = "GUARDIAN"
}

export enum BloodGroupTypes {
  A_POSITIVE = "A_POSITIVE",
  A_NEGATIVE = "A_NEGATIVE",
  B_POSITIVE = "B_POSITIVE",
  B_NEGATIVE = "B_NEGATIVE",
  AB_POSITIVE = "AB_POSITIVE",
  AB_NEGATIVE = "AB_NEGATIVE",
  O_POSITIVE = "O_POSITIVE",
  O_NEGATIVE = "O_NEGATIVE"
}

export enum MaritalStatusTypes {
  MARRIED = "MARRIED",
  SINGLE = "SINGLE",
  SEPARATED = "DIVORCED",
  WIDOWED = "WIDOWED"
}

export enum EmploymentAllocationTypes {
  FULL_TIME = "FULL_TIME",
  PART_TIME = "PART_TIME"
}

export enum EmploymentTypes {
  PERMANENT = "PERMANENT",
  INTERN = "INTERN",
  CONTRACT = "CONTRACT"
}

export enum AccountStatusTypes {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  TERMINATED = "TERMINATED"
}

export enum EEOJobCategoryTypes {
  EXECUTIVE = "EXECUTIVE_SENIOR_LEVEL_OFFICIALS_AND_MANAGERS",
  FIRST_MID_LEVEL = "FIRST_MID_LEVEL_OFFICIALS_AND_MANAGERS",
  PROFESSIONALS = "PROFESSIONALS",
  TECHNICIANS = "TECHNICIANS",
  SALES_WORKERS = "SALES_WORKERS",
  SUPPORT_WORKERS = "ADMINISTRATIVE_SUPPORT_WORKERS",
  CRAFT_WORKERS = "CRAFT_WORKERS",
  OPERATIVES = "OPERATIVES",
  LABORERS = "LABORERS_AND_HELPERS",
  SERVICE_WORKERS = "SERVICE_WORKERS"
}

export enum EthnicityTypes {
  AFRICAN = "AFRICAN",
  CARIBBEAN = "CARIBBEAN",
  INDIAN = "INDIAN",
  MELANESIAN = "MELANESIAN",
  AUSTRALASIAN_OR_ABORIGINAL = "AUSTRALASIAN_OR_ABORIGINAL",
  CHINESE = "CHINESE",
  GUAMANIAN = "GUAMANIAN",
  JAPANESE = "JAPANESE",
  KOREAN = "KOREAN",
  POLYNESIAN = "POLYNESIAN",
  EUROPEAN_OR_ANGLO_SAXON = "EUROPEAN_OR_ANGLO_SAXON",
  OTHER_PACIFIC_ISLANDER = "OTHER_PACIFIC_ISLANDER",
  LATIN_AMERICAN = "LATIN_AMERICAN",
  ARABIC = "ARABIC",
  VIETNAMESE = "VIETNAMESE",
  MICRONESIAN = "MICRONESIAN",
  DECLINED_TO_RESPOND = "DECLINED_TO_RESPOND",
  OTHER_HISPANIC = "OTHER_HISPANIC",
  US_OR_CANADIAN_INDIAN = "US_OR_CANADIAN_INDIAN",
  OTHER_ASIAN = "OTHER_ASIAN",
  PUERTO_RICAN = "PUERTO_RICAN",
  FILIPINO = "FILIPINO",
  MEXICAN = "MEXICAN",
  ALASKAN_NATIVE = "ALASKAN_NATIVE",
  CUBAN = "CUBAN"
}

export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  PEOPLE_ADMIN = "PEOPLE_ADMIN",
  PEOPLE_MANAGER = "PEOPLE_MANAGER",
  PEOPLE_EMPLOYEE = "PEOPLE_EMPLOYEE",
  LEAVE_ADMIN = "LEAVE_ADMIN",
  LEAVE_MANAGER = "LEAVE_MANAGER",
  LEAVE_EMPLOYEE = "LEAVE_EMPLOYEE",
  ATTENDANCE_ADMIN = "ATTENDANCE_ADMIN",
  ATTENDANCE_MANAGER = "ATTENDANCE_MANAGER",
  ATTENDANCE_EMPLOYEE = "ATTENDANCE_EMPLOYEE",
  ESIGN_EMPLOYEE = "ESIGN_EMPLOYEE",
  ESIGN_SENDER = "ESIGN_SENDER",
  ESIGN_ADMIN = "ESIGN_ADMIN",
  PM_ADMIN = "PM_ADMIN",
  PM_EMPLOYEE = "PM_EMPLOYEE",
  INVOICE_ADMIN = "INVOICE_ADMIN",
  INVOICE_MANAGER = "INVOICE_MANAGER",
  INVOICE_NONE = "INVOICE_NONE",
  CRM_ADMIN = "CRM_ADMIN",
  CRM_SALES_MANAGER = "CRM_SALES_MANAGER",
  CRM_SALES_REPRESENTATIVE = "CRM_SALES_REPRESENTATIVE",
  CRM_NONE = "CRM_NONE"
}

export enum NationalityEnum {
  AFGHAN = "Afghan",
  ALANDISH = "Ålandish",
  ALBANIAN = "Albanian",
  ALGERIAN = "Algerian",
  AMERICAN = "American",
  AMERICAN_ISLANDER = "American Islander",
  AMERICAN_SAMOAN = "American Samoan",
  ANDORRAN = "Andorran",
  ANGOLAN = "Angolan",
  ANGUILLIAN = "Anguillian",
  ANTARCTICAN = "Antarctican",
  ANTIGUAN_BARBUDA = "Antiguan, Barbudan",
  ARGENTINE = "Argentine",
  ARMENIAN = "Armenian",
  ARUBAN = "Aruban",
  AUSTRALIAN = "Australian",
  AUSTRIAN = "Austrian",
  AZERBAIJANI = "Azerbaijani",
  BAHAMIAN = "Bahamian",
  BAHRAINI = "Bahraini",
  BANGLADESHI = "Bangladeshi",
  BARBADIAN = "Barbadian",
  BELARUSIAN = "Belarusian",
  BELGIAN = "Belgian",
  BELIZEAN = "Belizean",
  BENINESE = "Beninese",
  BERMUDIAN = "Bermudian",
  BHUTANESE = "Bhutanese",
  BOLIVIAN = "Bolivian",
  BOSNIAN_HERZEGOVINIAN = "Bosnian, Herzegovinian",
  BRAZILIAN = "Brazilian",
  BRITISH = "British",
  BRUNEIAN = "Bruneian",
  BULGARIAN = "Bulgarian",
  BURKINABE = "Burkinabe",
  BURMESE = "Burmese",
  BURUNDIAN = "Burundian",
  CAMBODIAN = "Cambodian",
  CAMEROONIAN = "Cameroonian",
  CANADIAN = "Canadian",
  CAPE_VERDIAN = "Cape Verdian",
  CAYMANIAN = "Caymanian",
  CENTRAL_AFRICAN = "Central African",
  CHADIAN = "Chadian",
  CHANNEL_ISLANDER = "Channel Islander",
  CHILEAN = "Chilean",
  CHINESE = "Chinese",
  CHRISTMAS_ISLANDER = "Christmas Islander",
  COCOS_ISLANDER = "Cocos Islander",
  COLOMBIAN = "Colombian",
  COMORAN = "Comoran",
  CONGOLESE = "Congolese",
  COOK_ISLANDER = "Cook Islander",
  COSTA_RICAN = "Costa Rican",
  CROATIAN = "Croatian",
  CUBAN = "Cuban",
  CURACAOAN = "Curaçaoan",
  CYPRIOT = "Cypriot",
  CZECH = "Czech",
  DANISH = "Danish",
  DJIBOUTI = "Djibouti",
  DOMINICAN = "Dominican",
  DUTCH = "Dutch",
  EAST_TIMORESE = "East Timorese",
  ECUADOREAN = "Ecuadorean",
  EGYPTIAN = "Egyptian",
  EMIRATI = "Emirati",
  EQUATORIAL_GUINEAN = "Equatorial Guinean",
  ERITREAN = "Eritrean",
  ESTONIAN = "Estonian",
  ETHIOPIAN = "Ethiopian",
  FALKLAND_ISLANDER = "Falkland Islander",
  FAROESE = "Faroese",
  FIJIAN = "Fijian",
  FILIPINO = "Filipino",
  FINNISH = "Finnish",
  FRENCH = "French",
  FRENCH_POLYNESIAN = "French Polynesian",
  GABONESE = "Gabonese",
  GAMBIAN = "Gambian",
  GEORGIAN = "Georgian",
  GERMAN = "German",
  GHANAIAN = "Ghanaian",
  GIBRALTARIAN = "Gibraltar",
  GREEK = "Greek",
  GREENLANDIC = "Greenlandic",
  GRENADIAN = "Grenadian",
  GUADELOUPEAN = "Guadeloupian",
  GUAMANIAN = "Guamanian",
  GUATEMALAN = "Guatemalan",
  GUIANAN = "Guianan",
  GUINEA_BISSAUAN = "Guinea-Bissauan",
  GUINEAN = "Guinean",
  GUYANESE = "Guyanese",
  HAITIAN = "Haitian",
  HONDURAN = "Honduran",
  HONG_KONGER = "Hong Konger",
  HUNGARIAN = "Hungarian",
  ICELANDER = "Icelander",
  INDIAN = "Indian",
  INDONESIAN = "Indonesian",
  IRANIAN = "Iranian",
  IRAQI = "Iraqi",
  IRISH = "Irish",
  ISRAELI = "Israeli",
  ITALIAN = "Italian",
  IVORIAN = "Ivorian",
  JAMAICAN = "Jamaican",
  JAPANESE = "Japanese",
  JORDANIAN = "Jordanian",
  KAZAKHSTANI = "Kazakhstani",
  KENYAN = "Kenyan",
  KIRGHIZ = "Kirghiz",
  KOSOVAR = "Kosovar",
  KUWAITI = "Kuwaiti",
  LAOTIAN = "Laotian",
  LATVIAN = "Latvian",
  LEBANESE = "Lebanese",
  LIBERIAN = "Liberian",
  LIBYAN = "Libyan",
  LIECHTENSTEINER = "Liechtensteiner",
  LITHUANIAN = "Lithuanian",
  LUXEMBOURGER = "Luxembourger",
  MACEDONIAN = "Macedonian",
  MALAGASY = "Malagasy",
  MALAWIAN = "Malawian",
  MALAYSIAN = "Malaysian",
  MALTESE = "Maltese",
  MARSHALLESE = "Marshallese",
  MAURITIAN = "Mauritian",
  MEXICAN = "Mexican",
  MICRONESIAN = "Micronesian",
  MOLDOVAN = "Moldovan",
  MONGOLIAN = "Mongolian",
  MONTENEGRIN = "Montenegrin",
  MOROCCAN = "Moroccan",
  MOZAMBICAN = "Mozambican",
  NAMIBIAN = "Namibian",
  NAURUAN = "Nauruan",
  NEPALESE = "Nepalese",
  NEW_ZEALANDER = "New Zealander",
  NICARAGUAN = "Nicaraguan",
  NIGERIAN = "Nigerian",
  NORWEGIAN = "Norwegian",
  OMANI = "Omani",
  PAKISTANI = "Pakistani",
  PALAUAN = "Palauan",
  PANAMANIAN = "Panamanian",
  PARAGUAYAN = "Paraguayan",
  PERUVIAN = "Peruvian",
  POLISH = "Polish",
  PORTUGUESE = "Portuguese",
  PUERTO_RICAN = "Puerto Rican",
  QATARI = "Qatari",
  ROMANIAN = "Romanian",
  RUSSIAN = "Russian",
  RWANDAN = "Rwandan",
  SAUDI_ARABIAN = "Saudi Arabian",
  SENEGALESE = "Senegalese",
  SERBIAN = "Serbian",
  SINGAPOREAN = "Singaporean",
  SLOVAK = "Slovak",
  SLOVENE = "Slovene",
  SOUTH_AFRICAN = "South African",
  SOUTH_KOREAN = "South Korean",
  SPANISH = "Spanish",
  SWEDISH = "Swedish",
  SWISS = "Swiss",
  THAI = "Thai",
  TURKISH = "Turkish",
  UKRAINIAN = "Ukrainian",
  VENEZUELAN = "Venezuelan",
  VIETNAMESE = "Vietnamese",
  ZAMBIAN = "Zambian",
  ZIMBABWEAN = "Zimbabwean"
}

export enum RoleModuleEnum {
  PEOPLE = "people",
  LEAVE = "leave",
  ATTENDANCE = "attendance",
  ESIGN = "esign",
  INVOICE = "invoice",
  PM = "pm",
  CRM = "crm"
}

export enum RoleNameEnum {
  ADMIN = "Admin",
  MANAGER = "Manager",
  SENDER = "Sender",
  SALES_MANAGER = "Sales Manager",
  SALES_REPRESENTATIVE = "Sales Representative",
  NONE = "None"
}
